// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHvv4p2Ms2oGJRxujeeHXWA4tpMNbaBE',
    appId: '1:453488232417:android:26a133f44abf151585b4a0',
    messagingSenderId: '453488232417',
    projectId: 'grocery-app-f9b9c',
    storageBucket: 'grocery-app-f9b9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvy-T1F5QHMcwbZjeGUI4FOCNiVE4V-x0',
    appId: '1:453488232417:ios:332b9a601792510585b4a0',
    messagingSenderId: '453488232417',
    projectId: 'grocery-app-f9b9c',
    storageBucket: 'grocery-app-f9b9c.appspot.com',
    androidClientId: '453488232417-rqvbc77vkp25lj2ogamlh5p52a1l21dq.apps.googleusercontent.com',
    iosClientId: '453488232417-s0ggqnv94q97v95ecuuv7nf60n7dlafc.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvy-T1F5QHMcwbZjeGUI4FOCNiVE4V-x0',
    appId: '1:453488232417:ios:332b9a601792510585b4a0',
    messagingSenderId: '453488232417',
    projectId: 'grocery-app-f9b9c',
    storageBucket: 'grocery-app-f9b9c.appspot.com',
    androidClientId: '453488232417-rqvbc77vkp25lj2ogamlh5p52a1l21dq.apps.googleusercontent.com',
    iosClientId: '453488232417-s0ggqnv94q97v95ecuuv7nf60n7dlafc.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsR80roNmjAtIGookRw-GJjKYvUiqVfTc',
    appId: '1:453488232417:web:cab8ba9de778e94a85b4a0',
    messagingSenderId: '453488232417',
    projectId: 'grocery-app-f9b9c',
    authDomain: 'grocery-app-f9b9c.firebaseapp.com',
    storageBucket: 'grocery-app-f9b9c.appspot.com',
    measurementId: 'G-9NJ1JSCSMX',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsR80roNmjAtIGookRw-GJjKYvUiqVfTc',
    appId: '1:453488232417:web:4f60db5948cfd59685b4a0',
    messagingSenderId: '453488232417',
    projectId: 'grocery-app-f9b9c',
    authDomain: 'grocery-app-f9b9c.firebaseapp.com',
    storageBucket: 'grocery-app-f9b9c.appspot.com',
    measurementId: 'G-5X8718ZKJE',
  );

}